site_name: Jetson Cyber & AI Summer Camp
theme:
  name: material
  palette:
    primary: teal
    accent: light blue
  language: en

plugins:
  - search
  # - revealjs

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.highlight
  - pymdownx.tasklist
  - toc:
      permalink: true

nav:
  - Home: index.md
  - ğŸ”° Getting Started with Jetson:
      - âœ… sjsujetsontool Guide: curriculum/00_sjsujetsontool_guide.md
      - ğŸ“‹ sjsujetsontool Cheatsheet: curriculum/00b_sjsujetsontool_cheatsheet.md
      - ğŸ”§ Introduction to NVIDIA Jetson: curriculum/01a_nvidia_jetson.md
      - ğŸš€ CUDA Programming on Jetson: curriculum/01b_jetson_cuda.md
  - ğŸ§ Linux Fundamentals:
      - ğŸ’¡ Linux OS Basics: curriculum/02a_linux_basics.md
      - ğŸŒ Linux Networking Tools: curriculum/03a_linux_networking_tools.md
  - ğŸ¤– AI & LLM:
      - ğŸ§  Transformers & NLP Applications: curriculum/05_transformers_nlp_applications.md
      - ğŸš€ Large Language Models on Jetson: curriculum/06_llms_jetson.md
      - ğŸ“š NLP Applications & LLM Optimization: curriculum/07_nlp_applications_llm_optimization.md
      - âœï¸ Prompt Engineering & LangChain: curriculum/08_prompt_engineering_langchain_jetson.md
      - ğŸ” RAG Applications with LangChain: curriculum/09_rag_app_langchain_jetson.md
